/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package strings.palindrome;

import org.junit.Test;
import static org.junit.Assert.*;

public class PalindromeTest {
    @Test public void emptyStringShouldBeAPalindrome() {
        Palindrome empty = new Palindrome();
        assertTrue("Expected empty string to be a Palindrome.java", empty.isPalindrome(""));
    }
}
